version: "3.2"
services:
  app:
    build: .
    image: rails
    ports:
      - "80:3000"
    volumes:
      - ./:/home/deploy/app
      - bundlercache:/usr/local/bundle
    depends_on:
      - db
  
  db:
    image: postgres:11
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  bundlercache:
  postgresdata:
