version: "3"
services:
  app:
    build: .
    image: rails
    ports:
      - "80:3000"
    volumes:
      - ./:/home/deploy/app
      - ./tmp/bundle:/usr/local/bundle
    depends_on:
      - db
  
  db:
    image: postgres:11
    volumes:
      - ./database:/var/lib/postgresql/data

